# Generated by Django 6.0.5 on 2026-09-10 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('Heritage', 'Heritage & Architecture'), ('Nature', 'Nature & Eco-Tourism'), ('Adventure', 'Adventure & Outdoors'), ('Culture', 'Culture & Local Life'), ('Spiritual', 'Spiritual & Pilgrimage'), ('Food', 'Food & Culinary'), ('Wildlife', 'Wildlife & Sanctuaries'), ('Beach', 'Beach & Coastal'), ('Hill Station', 'Hill Station & Mountains')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('best_time', models.CharField(help_text='e.g. October to March', max_length=100)),
                ('estimated_cost', models.FloatField(default=500.0, help_text='Estimated cost per person in INR')),
                ('recommended_duration', models.FloatField(default=3.0, help_text='Recommended duration in hours')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField(default=4.5)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('tags', models.CharField(help_text='Pipe or comma separated keywords, e.g. History|Culture|Photography', max_length=255)),
                ('is_hidden_gem', models.BooleanField(db_index=True, default=False)),
                ('sustainability_score', models.FloatField(default=8.0, help_text='Eco score out of 10')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tourist Place',
                'verbose_name_plural': 'Tourist Places',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=200)),
                ('starting_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('num_days', models.IntegerField(default=3)),
                ('budget', models.FloatField(default=15000.0)),
                ('travel_type', models.CharField(default='Friends', max_length=50)),
                ('travel_pace', models.CharField(default='Balanced', max_length=50)),
                ('interests', models.CharField(max_length=255)),
                ('itinerary_json', models.JSONField(default=dict)),
                ('total_estimated_cost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_trips', to=settings.AUTH_USER_MODEL)),
                ('selected_places', models.ManyToManyField(related_name='trips', to='tourism.touristplace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='tourism.touristplace')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'place')},
            },
        ),
    ]
